import vtk
cylinder = vtk.vtkCylinderSource()
cylinder.SetResolution(8)
cylinderMapper = vtk.vtkPolyDataMapper()
cylinderMapper.SetInputConnection(cylinder.GetOutputPort())
cylinderActor = vtk.vtkActor()
cylinderActor.SetMapper(cylinderMapper)
readline.write_history_file("4.1.py")
p=cylinderActor.GetProperty()
p.SetColor("tomato")
p.SetColor(1,0,0,)
p.SetColor(1,0,0)
cylinderActor.RotateX(30.)
cylinderActor.RotateY(-45.)
p.SetColor(1.,.3882,.2784)
ren1 = vtk.vtkRenderer()
renwin = vtk.vtkRenderWindow()
renwin.AddRenderer(ren1)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renwin)
ren1.AddActor(cylinderActor)
ren1.SetBackground(.1,.2,.4)
renwin.SetSize(200,200)
iren.Initialize()

